#!/bin/bash

#!/bin/bash
USERNAME=student
count=0
while read hostname ; do
    SCRIPT='caffeinate -u;'
    >&2 echo $SCRIPT;
    ssh -n -o BatchMode=yes student@${hostname} "${SCRIPT}" &
    count=`expr $count + 1`
done<hosts

>&2 echo "all started, waiting for termination";

while [ $count -gt 0 ]; do
    wait $pids
    count=`expr $count - 1`
done
